<!DOCTYPE html>
<html>
  <head>
    <!-- Refresh every 30 seconds -->
    <meta http-equiv="refresh" content="30" />
    <style type="text/css">
      table {
        width:100%;
        text-align: center;
      }
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
      th, td {
        padding: 5px;
        text-align: center;
      }
      table tr:nth-child(2n) {
        background-color: #eee;
      }
      table tr:nth-child(2n+1) {
        background-color:#fff;
      }
      th{
        background-color: black;
        color: white;
      }
    </style>
  </head>
  <body>
    <table >
      <tr>
        <th>Team</th>
        <th>Complete</th>
        <th>Total Time</th>
<?php
  for ($i=1; $i<=5; $i++) {
    echo "        <th colspan = \"2\">Problem ".$i."</th>\n";
  }
?>
      </tr>
      <tr>
        <th colspan = "3"></th>
<?php
  for ($i=1; $i<=5; $i++) {
    echo "        <th>Attempts</th>\n";
    echo "        <th>Time</th>\n";
  }
?>
      </tr>
<?php
  $handle = fopen("/home/az/Git/DHS-HSPC/Scoreboard/sample.scores", "r");
  if ($handle) {
  while (($line = fgets($handle)) !== false) {
    $parts      = split('=\|=', rtrim($line, "\n"));
    $total_time = strtotime("00:00:00");
    $complete   = 0;
    
    echo "      <tr>\n";
    echo "        <td>".$parts[0]."</td>\n";
    
    for($i=2; $i<count($parts); $i+=2) {
      $time       =  strtotime($parts[$i]);
      $total_time += $time - strtotime("00:00:00");
      if($time > strtotime("00:00:00"))
        $complete++;
      
    }
    echo "        <td>".$complete."</td>\n";
    echo "        <td>".date("H:i:s", $total_time)."</td>\n";
    
    for($i=1; $i<count($parts); $i+=2) {
      echo "        <td>".$parts[$i]."</td>\n";
      echo "        <td>".$parts[$i+1]."</td>\n";
    }
  }

  fclose($handle);
  }
  else {
    echo "<td> No scores found<td<>\n";
  } 
?>
    </table>
  </body>
</html>
