<!DOCTYPE html>
<html>
  <head>
    <!-- Refresh every 30 seconds -->
    <meta http-equiv="refresh" content="30" />
    <style type="text/css">
      table {
        width:100%;
        text-align: center;
      }
      table, th, td {
        border: 1px solid black;
        border-collapse: collapse;
      }
      th, td {
        padding: 5px;
        text-align: center;
      }
      table tr:nth-child(2n) {
        background-color: #eee;
      }
      table tr:nth-child(2n+1) {
        background-color:#fff;
      }
      th{
        background-color: black;
        color: white;
      }
    </style>
  </head>
  <body>
    <table >
      <tr>
        <th>Team</th>
        <th>Done</th>
        <th>Total Time</th>
<?php
  $number_of_problems = 9;
  $size_of_name       = 40; //In bytes, ASCII representation of chars
  $size_of_data       = 8;  //Both attempts AND time
  for ($i=1; $i<=$number_of_problems; $i++) {
    echo "        <th colspan = \"2\">Problem ".$i."</th>\n";
  }
?>
      </tr>
      <tr>
        <th colspan = "3"></th>
<?php
  for ($i=1; $i<=$number_of_problems; $i++) {
    echo "        <th>Trys</th>\n";
    echo "        <th>Time</th>\n";
  }
?>
      </tr>
<?php
  $handle = fopen("/home/az/Git/DHS-HSPC/Scoreboard/scores.db", "rb");
  $read = 0;
  if ($handle) {
    while (ftell($handle) < fstat($handle)['size']) {
      $total_time = 0;
      $complete   = 0;
      $table      = "";
      
      $data       = fread($handle, $size_of_name);
      $parts      = unpack("c*", $data);
      echo "      <tr>\n";
      
      echo "        <td>";
      for($i=1; $parts[$i] != 0; $i++) {
        if ($parts[$i] >= 32) echo chr($parts[$i]);
      }
      echo "</td>\n";
      
      for($i=0; $i<$number_of_problems; $i++) {
        $data        = fread($handle, $size_of_data);
        $parts       = unpack("i*", $data);
        $time        = $parts[2];
        
        $table      .= "        <td>".$parts[1]."</td>\n";
        $table      .= "        <td>".gmdate("H:i:s", $time)."</td>\n";
        
        $total_time += $time;
        if($time > 0) $complete++;
      }
      
      echo "        <td>".$complete."</td>\n";
      echo "        <td>".gmdate("H:i:s", $total_time)."</td>\n";
      echo $table;
      
      echo "      </tr>\n";
    }

    fclose($handle);
  }
  else {
    echo "      <tr>\n";
    echo "        <td colspan = \"".(3+2*$number_of_problems)."\"> No scores found</td>\n";
    echo "      </tr>\n";
  } 
?>
    </table>
  </body>
</html>
